# Generated by Django 2.2.12 on 2020-05-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('category', models.SmallIntegerField(choices=[(1, 'Groceries'), (2, 'Cleaning products'), (3, 'Cosmetics'), (4, 'Beauty'), (5, 'Entertainment'), (6, 'Children'), (7, 'Transport'), (8, 'Education'), (9, 'Bills'), (10, 'Clothing'), (11, 'Health'), (12, 'Alcohol'), (13, 'Cigarettes'), (14, 'Taxes'), (15, 'Other')])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget_app.BudgetInfo')),
            ],
        ),
    ]
