# Generated by Django 2.2.12 on 2020-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction',
            field=models.SmallIntegerField(choices=[(1, 'Cash'), (2, 'Card')], default=2),
        ),
    ]
