# Generated by Django 2.2.12 on 2020-05-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_expense_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetinfo',
            old_name='budget',
            new_name='balance',
        ),
    ]
