# Generated by Django 2.2.12 on 2020-05-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_auto_20200502_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
    ]
