# Generated by Django 2.2.12 on 2020-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20200503_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Groceries'), (2, 'Cleaning products'), (3, 'Cosmetics'), (4, 'Beauty'), (5, 'Entertainment'), (6, 'Children'), (7, 'Transport'), (8, 'Education'), (9, 'Bills'), (10, 'Clothing'), (11, 'Health'), (12, 'Alcohol'), (13, 'Cigarettes'), (14, 'Taxes'), (15, 'Accomodation'), (16, 'Other')]),
        ),
    ]
