# Generated by Django 2.2.12 on 2020-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_auto_20200504_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.SmallIntegerField(choices=[(1, 'card'), (2, 'cash')], default=1),
        ),
    ]
