# Generated by Django 2.2.12 on 2020-05-08 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0006_auto_20200504_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.SmallIntegerField(choices=[(1, 'card'), (2, 'cash'), (3, 'transfer'), (4, 'other')], default=1),
        ),
    ]
