# Generated by Django 2.2.12 on 2020-05-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_auto_20200508_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetinfo',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
