# Generated by Django 2.2.12 on 2020-05-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_budgetinfo_edited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetinfo',
            name='edited_on',
        ),
    ]
