# Generated by Django 2.2.12 on 2020-05-08 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_remove_budgetinfo_edited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
