# Generated by Django 2.2.12 on 2020-05-08 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_remove_expense_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
