# Generated by Django 2.2.12 on 2020-05-08 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0013_auto_20200508_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
