# Generated by Django 2.2.12 on 2020-05-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0014_expense_date_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='dated_on',
        ),
    ]
