services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWD: ${USER_PASSWD}
    image: budget:1.0
    container_name: tracker
    volumes:
      - .:/tracker_volume
    ports:
      - "8000:8000"
    env_file:
      - .env_test
      - .env
    depends_on:
      - db
    networks:
      - tracker_network

  db:
    image: postgres:16-alpine3.20
    container_name: tracker_db
    env_file:
      - .env_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - tracker_network

volumes:
  postgres_volume:
    driver: local
    name: postgres_data

networks:
  tracker_network:
    driver: bridge