version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    env_file:
      - .env_docker
      - .env_dev
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.20
    container_name: postgres-db
    env_file:
      - .env_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: