apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: mcwilkdev/budget:1.3.1  # to be updated (GitOps)
          ports:
            - containerPort: 8000  # port inside the container (Django listens here)
          env:
            - name: DJANGO_ENV
              value: staging
            - name: DEBUG
              value: "False"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              value: "tracker-local,localhost,127.0.0.1"
            - name: POSTGRES_DB
              value: "budget_app_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: service-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_SUPERUSER_PASSWORD
            - name: DJANGO_GENERIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_GENERIC_USERNAME
            - name: DJANGO_GENERIC_EMAIL
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_GENERIC_EMAIL
            - name: DJANGO_GENERIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tracker-secret
                  key: DJANGO_GENERIC_PASSWORD