apiVersion: batch/v1
kind: Job
metadata:
  name: budget-migrate
spec:
  template:
    spec:
      containers:
      - name: migrations
        image: mcwilkdev/budget:1.3.1
        env:
        - name: DJANGO_ENV
          value: staging
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tracker-secret
              key: SECRET_KEY
        - name: POSTGRES_DB
          value: "budget_app_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: service-postgres
        - name: POSTGRES_PORT
          value: "5432"
        command: ["python", "manage.py", "migrate"]
      restartPolicy: Never
  backoffLimit: 4