apiVersion: v1
kind: Secret
metadata:
  name: secret-postgres
type: Opaque
data:
  POSTGRES_DB: YnVkZ2V0X2FwcF9kYg==
  POSTGRES_USER: YnVkZ2V0X2FwcF91c2VyX3Rlc3Q=
  POSTGRES_PASSWORD: d2VsY29tZVRvVGhlRGphbmdvVGVzdA==
