apiVersion: v1
kind: Secret
metadata:
  name: tracker-secret
type: Opaque
data:
  SECRET_KEY: IzlwKV9oKWo3d24tOWhedGdzOWM3cGorNmdxPStsKHB1bmJfeGUwaGN5KjN6JSkwX18=
  DJANGO_SUPERUSER_USERNAME: YWRtaW5fc3RhZ2luZw==
  DJANGO_SUPERUSER_EMAIL: YnVkZ2V0X2FkbWluX3N0YWdpbmdAZXhhbXBsZS5jb20=
  DJANGO_SUPERUSER_PASSWORD: YnVkZ2V0X2FkbWluX3N0YWdpbmcx
  DJANGO_GENERIC_USERNAME: c3RhZ2luZ3VzZXIx
  DJANGO_GENERIC_EMAIL: c3RhZ2luZ3VzZXIxQGV4YW1wbGUuY29t
  DJANGO_GENERIC_PASSWORD: c3RhZ2luZ3VzZXIx