apiVersion: v1
kind: Service
metadata:
  name: tracker-service
spec:
  selector:
    app: tracker
  type: ClusterIP       # default type (not needed to declare), other: NodePort, LoadBalancer
  ports:
    - protocol: TCP
      port: 8000        # Service listens here
      targetPort: 8000  # Traffic goes to pod here (the port where Django listens to)