name: test_ci
on:
  push:
    branches: [ "*" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Static code checks with linter
        run: pylint budget_app/admin.py