name: build & deliver
on:
  push:
    tags:
      - '1.*.*'

jobs:
  build-push-update:
    name: Build image and push to DockerHub
    runs-on: ubuntu-latest

    env:
      USER_NAME: "appuser"
      USER_GROUP: "appgroup"
      USER_GROUP_ID: 1001

    steps:
      - name: Clone code to VM (runner)
        uses: actions/checkout@v3

      - name: Set-up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          
      - name: Build and push
        run: |
          docker build \
          --build-arg USER_NAME=${{ env.USER_NAME }} \
          --build-arg USER_GROUP=${{ env.USER_GROUP }} \
          --build-arg USER_GROUP_ID=${{ env.USER_GROUP_ID }} \
          -t ${DOCKERHUB_USER}/budget:${IMAGE_TAG} .
          docker push ${DOCKERHUB_USER}"/budget:${IMAGE_TAG}
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}