name: test_ci
on:
  push:
    branches: [ "*" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Clone repo to VM (runner)
        uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Install linter
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Run linter
        run: pylint budget_app/admin.py