name: build & deliver
on:
  push:
    tags:
      - '1.*.*'

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code to VM (runner)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password
          
      - name: Build and push
        run: |
          docker build -t "${DOCKERHUB_USER}"/budget:${IMAGE_TAG}" .
          docker push "${DOCKERHUB_USER}"/budget:${IMAGE_TAG}"
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}