name: build & deliver
on:
  # Workflow runs whenever new tag is created locally ang pushed to the repo
  push:
    tags:
      - '1.*.*'

jobs:
  build-push-update:
    name: Build image and push to DockerHub
    runs-on: ubuntu-latest

    env:
      USER_NAME: "appuser"
      USER_GROUP: "appgroup"
      USER_GROUP_ID: 1001
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Clone code to VM (runner)
        uses: actions/checkout@v3

      - name: Set-up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          
      - name: Build and push
        run: |
          docker build \
          --build-arg USER_NAME=${{ env.USER_NAME }} \
          --build-arg USER_GROUP=${{ env.USER_GROUP }} \
          --build-arg USER_GROUP_ID=${{ env.USER_GROUP_ID }} \
          -t ${DOCKERHUB_USER}/budget:${IMAGE_TAG} .
          docker push ${{ env.DOCKERHUB_USER }}/budget:${IMAGE_TAG}

      - name: Update deployment with a new tag
        run: |
          sed -i "s|image: ${{ env.DOCKERHUB_USER }}/budget:.*|image: ${{ env.DOCKERHUB_USER }}/budget:${IMAGE_TAG}|" k8s/deployment.yaml

      - name: Create PR for a new tag
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update deployment image tag to ${{ env.IMAGE_TAG }}"
          title: "Deployment tag-${{ env.IMAGE_TAG }}"
          body: "Automatic PR to update app deployment image tag"
          branch: deploy/tag-${{ env.IMAGE_TAG }}
          base: master
          assignees: mcwilk
          reviewers: mcwilk
          labels: |
            deployment
            gitops
