name: test_ci
on:
  push:
    branches: [ "*" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Clone repo to VM (runner)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch origin
        run: git fetch origin

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y bc

      - name: Get list of modified Python files
        id: changed-files
        run: |
          CHANGED=$(git diff --name-only origin/master...HEAD -- '*.py')
          echo "Changed files: $CHANGED"
          echo "files=$CHANGED >> GITHUB_OUTPUT"

      - name: Run linter and get results
        run: |
          SCORE=$(pylint ${{ steps.changed-files.outputs.files }} | grep 'Your code has been rated' | awk '{print $7}' | cut -d'/' -f1)
          LIMIT=9.9
          COMPARE=$(echo "$SCORE < $LIMIT" | bc)
          if [ "$COMPARE" -eq 1 ]; then
            echo "Static check rating is too low: $SCORE/10.0 - required: $LIMIT"
            exit 1
          else
            echo "Static check rating is OK ($SCORE/10.0)"
          fi